title: Jaeci
author: Jaeci Johnston
email: jajoh14@ilstu.edu
description: > # this means to ignore newlines until "baseurl:"
  Creative Technologies 201 Project, Spring 2020

# social links
github_username: jaeci # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
